persistence:
  enabled: true
  storageClass: ""
  size: 8Gi

serviceAccount:
  create: false
  name: jenkins-sa

rbac:
  create: false

controller:
  admin:
    username: admin
    password: admin

resources:
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

installPlugins:
  - kubernetes:1.29.2
  - workflow-aggregator:2.6
  - workflow-job:2.40
  - credentials-binding:1.24
  - git:4.10.0
  - configuration-as-code:1.51
  - kubernetes-credentials-provider:0.19

agent:
  volumes:
    - type: EmptyDir
      mountPath: /home/jenkins/agent
      name: workspace-volume

  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

JCasC:
  enabled: true
  configScripts:
    jenkins-config: |
      jenkins:
        authorizationStrategy: "loggedInUsersCanDoAnything"
        securityRealm: "legacy"
